# Modeling

In [1]:
from datetime import datetime
start_time = datetime.now()

# Libraries to load
#!pip install lightgbm
# conda install -c conda-forge lightgbm
# !conda install lightgbm --y

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

import lightgbm as lgb
import numpy as np
%matplotlib inline

print('LOAD DURATION: ', datetime.now() - start_time) # load time about 30 seconds

LOAD DURATION:  0:00:01.705052

In [2]:
vars = pd.read_csv('vars_30.csv')

In [3]:
vars.head()

,fulladdress_count_30,ssn_dob_count_30,homephone_unique_count_for_ssn_name_dob_3,address_unique_count_for_name_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_ssn_address_30,address_unique_count_for_dob_30,address_unique_count_for_ssn_zip5_60,address_unique_count_for_name_dob_60,address_unique_count_for_ssn_homephone_30,...,address_unique_count_for_ssn_30,homephone_unique_count_for_ssn_dob_3,address_unique_count_for_name_dob_30,address_unique_count_for_ssn_firstname_30,name_dob_count_7,address_unique_count_for_ssn_name_60,address_unique_count_for_name_30,address_unique_count_for_name_homephone_30,record,fraud_label
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,3,0
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,4,0
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,5,0

In [4]:
vars.columns

Index(['fulladdress_count_30', 'ssn_dob_count_30',
       'homephone_unique_count_for_ssn_name_dob_3',
       'address_unique_count_for_name_homephone_60',
       'fulladdress_unique_count_for_ssn_30',
       'fulladdress_unique_count_for_ssn_address_30',
       'address_unique_count_for_dob_30',
       'address_unique_count_for_ssn_zip5_60',
       'address_unique_count_for_name_dob_60',
       'address_unique_count_for_ssn_homephone_30',
       'homephone_unique_count_for_ssn_fulladdress_3',
       'address_unique_count_for_ssn_dob_30',
       'homephone_unique_count_for_ssn_address_3',
       'fulladdress_unique_count_for_name_fulladdress_30',
       'address_unique_count_for_ssn_address_30', 'ssn_count_30',
       'address_unique_count_for_dob_homephone_30',
       'address_unique_count_for_ssn_name_dob_30',
       'fulladdress_unique_count_for_ssn_firstname_30',
       'ssn_name_dob_count_30', 'homephone_unique_count_for_ssn_3',
       'fulladdress_homephone_count_30', 'address_unique_count_for_ssn_30',
       'homephone_unique_count_for_ssn_dob_3',
       'address_unique_count_for_name_dob_30',
       'address_unique_count_for_ssn_firstname_30', 'name_dob_count_7',
       'address_unique_count_for_ssn_name_60',
       'address_unique_count_for_name_30',
       'address_unique_count_for_name_homephone_30', 'record', 'fraud_label'],
      dtype='object')

In [5]:
# use this to cap variables. For some problems it helps
Clip = 10

In [6]:
vars['fraud_label'].sum()

14393

In [7]:
vars.head(10)

,fulladdress_count_30,ssn_dob_count_30,homephone_unique_count_for_ssn_name_dob_3,address_unique_count_for_name_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_ssn_address_30,address_unique_count_for_dob_30,address_unique_count_for_ssn_zip5_60,address_unique_count_for_name_dob_60,address_unique_count_for_ssn_homephone_30,...,address_unique_count_for_ssn_30,homephone_unique_count_for_ssn_dob_3,address_unique_count_for_name_dob_30,address_unique_count_for_ssn_firstname_30,name_dob_count_7,address_unique_count_for_ssn_name_60,address_unique_count_for_name_30,address_unique_count_for_name_homephone_30,record,fraud_label
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,3,0
3,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,4,0
4,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,5,0
5,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,6,0
6,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,7,0
7,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,8,0
8,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,9,0
9,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,10,0

In [8]:
vars.shape

(1000000, 32)

In [9]:
vars.describe()

,fulladdress_count_30,ssn_dob_count_30,homephone_unique_count_for_ssn_name_dob_3,address_unique_count_for_name_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_ssn_address_30,address_unique_count_for_dob_30,address_unique_count_for_ssn_zip5_60,address_unique_count_for_name_dob_60,address_unique_count_for_ssn_homephone_30,...,address_unique_count_for_ssn_30,homephone_unique_count_for_ssn_dob_3,address_unique_count_for_name_dob_30,address_unique_count_for_ssn_firstname_30,name_dob_count_7,address_unique_count_for_ssn_name_60,address_unique_count_for_name_30,address_unique_count_for_name_homephone_30,record,fraud_label
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.064624,1.046097,1.445475,1.066300,1.036240,1.036240,1.051915,1.063675,1.068471,1.051180,...,1.049553,1.445461,1.052149,1.049648,1.025181,1.063814,1.049317,1.051052,500000.500000,0.014393
std,0.633831,0.496315,0.858345,0.700813,0.608032,0.608032,0.640342,0.699142,0.702565,0.640027,...,0.638747,0.858339,0.640795,0.638824,0.451262,0.699278,0.638474,0.639856,288675.278933,0.119104
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,250000.750000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,500000.500000,0.000000
75%,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,750000.250000,0.000000
max,30.000000,34.000000,32.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,32.000000,30.000000,30.000000,34.000000,30.000000,30.000000,30.000000,1000000.000000,1.000000

In [10]:
record_save = vars['record']
Y_save = pd.DataFrame(vars.loc[:,'fraud_label'])
Y_save.head()

   fraud_label
0            0
1            1
2            0
3            0
4            0

## Scale and truncate field values

In [11]:
X_no_scaling = vars.drop(columns = ['record','fraud_label'])
X_no_scaling.describe()

,fulladdress_count_30,ssn_dob_count_30,homephone_unique_count_for_ssn_name_dob_3,address_unique_count_for_name_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_ssn_address_30,address_unique_count_for_dob_30,address_unique_count_for_ssn_zip5_60,address_unique_count_for_name_dob_60,address_unique_count_for_ssn_homephone_30,...,homephone_unique_count_for_ssn_3,fulladdress_homephone_count_30,address_unique_count_for_ssn_30,homephone_unique_count_for_ssn_dob_3,address_unique_count_for_name_dob_30,address_unique_count_for_ssn_firstname_30,name_dob_count_7,address_unique_count_for_ssn_name_60,address_unique_count_for_name_30,address_unique_count_for_name_homephone_30
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.064624,1.046097,1.445475,1.066300,1.036240,1.036240,1.051915,1.063675,1.068471,1.051180,...,1.445197,1.048207,1.049553,1.445461,1.052149,1.049648,1.025181,1.063814,1.049317,1.051052
std,0.633831,0.496315,0.858345,0.700813,0.608032,0.608032,0.640342,0.699142,0.702565,0.640027,...,0.858084,0.507682,0.638747,0.858339,0.640795,0.638824,0.451262,0.699278,0.638474,0.639856
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,30.000000,34.000000,32.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,32.000000,30.000000,30.000000,32.000000,30.000000,30.000000,34.000000,30.000000,30.000000,30.000000

In [12]:
X_no_scaling=X_no_scaling.iloc[:,0:20]

In [13]:
X_no_scaling.shape

(1000000, 20)

In [14]:
X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()

In [15]:
X.shape

(1000000, 20)

In [16]:
# push in any outlier values
cols = X.columns
X.loc[:,cols] = X[cols].clip(upper=Clip)
X.loc[:,cols] = X[cols].clip(lower=-1*Clip)
# X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()
X.describe()

,fulladdress_count_30,ssn_dob_count_30,homephone_unique_count_for_ssn_name_dob_3,address_unique_count_for_name_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_ssn_address_30,address_unique_count_for_dob_30,address_unique_count_for_ssn_zip5_60,address_unique_count_for_name_dob_60,address_unique_count_for_ssn_homephone_30,homephone_unique_count_for_ssn_fulladdress_3,address_unique_count_for_ssn_dob_30,homephone_unique_count_for_ssn_address_3,fulladdress_unique_count_for_name_fulladdress_30,address_unique_count_for_ssn_address_30,ssn_count_30,address_unique_count_for_dob_homephone_30,address_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_firstname_30,ssn_name_dob_count_30
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,-0.018176,-0.017649,-0.005878,-0.016841,-0.019877,-0.019877,-0.018240,-0.016943,-0.016732,-0.018278,-0.005883,-0.018211,-0.005883,-0.019904,-0.018364,-0.017667,-0.018196,-0.018205,-0.019874,-0.017661
std,0.631721,0.571302,0.909729,0.686509,0.572323,0.572323,0.634520,0.683961,0.689498,0.633134,0.909651,0.635236,0.909650,0.571322,0.630404,0.587739,0.635702,0.635426,0.572419,0.570790
min,-0.101958,-0.092879,-0.518993,-0.094604,-0.059602,-0.059602,-0.081074,-0.091076,-0.097459,-0.079965,-0.518877,-0.081590,-0.518867,-0.059105,-0.077578,-0.099006,-0.082208,-0.081761,-0.059674,-0.092594
25%,-0.101958,-0.092879,-0.518993,-0.094604,-0.059602,-0.059602,-0.081074,-0.091076,-0.097459,-0.079965,-0.518877,-0.081590,-0.518867,-0.059105,-0.077578,-0.099006,-0.082208,-0.081761,-0.059674,-0.092594
50%,-0.101958,-0.092879,-0.518993,-0.094604,-0.059602,-0.059602,-0.081074,-0.091076,-0.097459,-0.079965,-0.518877,-0.081590,-0.518867,-0.059105,-0.077578,-0.099006,-0.082208,-0.081761,-0.059674,-0.092594
75%,-0.101958,-0.092879,0.646040,-0.094604,-0.059602,-0.059602,-0.081074,-0.091076,-0.097459,-0.079965,0.646440,-0.081590,0.646454,-0.059105,-0.077578,-0.099006,-0.082208,-0.081761,-0.059674,-0.092594
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [17]:
# separate data into modeling (traintest) and out of time

X_trntst = X[38511:833507]  # remove the first 2 weeks of records since their variables aren't well formed
Y_trntst = Y_save[38511:833507]
X_oot = X[833507:]
Y_oot = Y_save[833507:]

In [18]:
niter = 0
nitermax = 1
FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
X_oot_orig = X_oot.copy()
pd.options.mode.chained_assignment = None  # default='warn'

In [19]:
# %%time
# # Logistic regression

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = LogisticRegression(penalty='elasticnet',solver='saga', l1_ratio = 0.2)
 
#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

## Models. You can comment out any of these cells and just explore one model type. You can also just rerun that single cell multiple times as you explore different model hyperparameters.

In [20]:
# %%time
# # Single DT

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = DecisionTreeClassifier(max_depth = 20, min_samples_split = 400, min_samples_leaf=60) # criterion = 'entropy',splitter = 'random'
 
#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

In [21]:
# %%time
# # RF

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = RandomForestClassifier(n_estimators = 50,  max_depth=20, min_samples_split=2, min_samples_leaf=1, max_features = 5) # criterion = 'entropy'

#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

In [22]:
# %%time
# # BT

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = lgb.LGBMClassifier(max_depth = 5,  n_estimators=300, min_child_samples=30) #learning_rate=0.01, subsample=0.7

#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

In [23]:
# %%time
# # NN

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = MLPClassifier(hidden_layer_sizes=(10, 10))

#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

In [24]:
# %%time
# # KNN

# for niter in range(nitermax):    
#     X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)

#     model = KNeighborsClassifier() 

#     X_oot = X_oot_orig.copy()
#     X_trn_save = X_trn.copy()
#     Y_trn_save = Y_trn.copy()

#     model.fit(X_trn, Y_trn.values.ravel())   

#     predictions = model.predict_proba(X_trn_save)[:,1]
#     X_trn['predicted'] = predictions
#     X_trn['fraud_label'] = Y_trn_save['fraud_label']
#     topRows = int(round(X_trn.shape[0]*0.03))
#     temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_tst)[:,1]
#     X_tst['predicted']=predictions
#     X_tst['fraud_label'] = Y_tst['fraud_label']
#     topRows = int(round(X_tst.shape[0]*0.03))
#     temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

#     predictions = model.predict_proba(X_oot)[:,1]
#     X_oot['predicted']=predictions
#     X_oot['fraud_label'] = Y_oot['fraud_label']
#     topRows = int(round(X_oot.shape[0]*0.03))
#     temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
#     needed = temp.loc[:,'fraud_label']
#     FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
#     print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
# print(FDR3.mean())

In [ ]:
%%time
# Support Vector Machine

for niter in range(nitermax):    
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .25)

    model = SVC(C=0.3,kernel='poly', gamma='scale',probability=True)

    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    model.fit(X_trn, Y_trn.values.ravel())   

    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
    
print(FDR3.mean())

In [ ]:
print('duration: ', datetime.now() - start_time)